package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.GameRule;
import org.linlinjava.litemall.db.domain.GameRuleExample;

public interface GameRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    long countByExample(GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int deleteByExample(GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int insert(GameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int insertSelective(GameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    GameRule selectOneByExample(GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    GameRule selectOneByExampleSelective(@Param("example") GameRuleExample example, @Param("selective") GameRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    List<GameRule> selectByExampleSelective(@Param("example") GameRuleExample example, @Param("selective") GameRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    List<GameRule> selectByExample(GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    GameRule selectByPrimaryKeySelective(@Param("ruleId") Integer ruleId, @Param("selective") GameRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    GameRule selectByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameRule record, @Param("example") GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameRule record, @Param("example") GameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameRule record);
}