package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.GameTree;
import org.linlinjava.litemall.db.domain.GameTreeExample;

public interface GameTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    long countByExample(GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int deleteByExample(GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer treeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int insert(GameTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int insertSelective(GameTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    GameTree selectOneByExample(GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    GameTree selectOneByExampleSelective(@Param("example") GameTreeExample example, @Param("selective") GameTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    List<GameTree> selectByExampleSelective(@Param("example") GameTreeExample example, @Param("selective") GameTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    List<GameTree> selectByExample(GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    GameTree selectByPrimaryKeySelective(@Param("treeId") Integer treeId, @Param("selective") GameTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    GameTree selectByPrimaryKey(Integer treeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameTree record, @Param("example") GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameTree record, @Param("example") GameTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameTree record);
}