package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.GameRuleItem;
import org.linlinjava.litemall.db.domain.GameRuleItemExample;

public interface GameRuleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    long countByExample(GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int deleteByExample(GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int insert(GameRuleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int insertSelective(GameRuleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    GameRuleItem selectOneByExample(GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    GameRuleItem selectOneByExampleSelective(@Param("example") GameRuleItemExample example, @Param("selective") GameRuleItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    List<GameRuleItem> selectByExampleSelective(@Param("example") GameRuleItemExample example, @Param("selective") GameRuleItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    List<GameRuleItem> selectByExample(GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    GameRuleItem selectByPrimaryKeySelective(@Param("itemId") Integer itemId, @Param("selective") GameRuleItem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    GameRuleItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GameRuleItem record, @Param("example") GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GameRuleItem record, @Param("example") GameRuleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameRuleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameRuleItem record);
}