package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class GameRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_flag
     *
     * @mbg.generated
     */
    private String ruleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_opt_pre
     *
     * @mbg.generated
     */
    private String ruleOptPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_opt
     *
     * @mbg.generated
     */
    private String ruleOpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_name
     *
     * @mbg.generated
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_desc
     *
     * @mbg.generated
     */
    private String ruleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_item
     *
     * @mbg.generated
     */
    private Integer ruleItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_rate_pre
     *
     * @mbg.generated
     */
    private Double ruleRatePre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_rate
     *
     * @mbg.generated
     */
    private Double ruleRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.rule_level
     *
     * @mbg.generated
     */
    private Integer ruleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rule.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_id
     *
     * @return the value of game_rule.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_id
     *
     * @param ruleId the value for game_rule.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_flag
     *
     * @return the value of game_rule.rule_flag
     *
     * @mbg.generated
     */
    public String getRuleFlag() {
        return ruleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_flag
     *
     * @param ruleFlag the value for game_rule.rule_flag
     *
     * @mbg.generated
     */
    public void setRuleFlag(String ruleFlag) {
        this.ruleFlag = ruleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_opt_pre
     *
     * @return the value of game_rule.rule_opt_pre
     *
     * @mbg.generated
     */
    public String getRuleOptPre() {
        return ruleOptPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_opt_pre
     *
     * @param ruleOptPre the value for game_rule.rule_opt_pre
     *
     * @mbg.generated
     */
    public void setRuleOptPre(String ruleOptPre) {
        this.ruleOptPre = ruleOptPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_opt
     *
     * @return the value of game_rule.rule_opt
     *
     * @mbg.generated
     */
    public String getRuleOpt() {
        return ruleOpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_opt
     *
     * @param ruleOpt the value for game_rule.rule_opt
     *
     * @mbg.generated
     */
    public void setRuleOpt(String ruleOpt) {
        this.ruleOpt = ruleOpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_name
     *
     * @return the value of game_rule.rule_name
     *
     * @mbg.generated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_name
     *
     * @param ruleName the value for game_rule.rule_name
     *
     * @mbg.generated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_desc
     *
     * @return the value of game_rule.rule_desc
     *
     * @mbg.generated
     */
    public String getRuleDesc() {
        return ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_desc
     *
     * @param ruleDesc the value for game_rule.rule_desc
     *
     * @mbg.generated
     */
    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_item
     *
     * @return the value of game_rule.rule_item
     *
     * @mbg.generated
     */
    public Integer getRuleItem() {
        return ruleItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_item
     *
     * @param ruleItem the value for game_rule.rule_item
     *
     * @mbg.generated
     */
    public void setRuleItem(Integer ruleItem) {
        this.ruleItem = ruleItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_rate_pre
     *
     * @return the value of game_rule.rule_rate_pre
     *
     * @mbg.generated
     */
    public Double getRuleRatePre() {
        return ruleRatePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_rate_pre
     *
     * @param ruleRatePre the value for game_rule.rule_rate_pre
     *
     * @mbg.generated
     */
    public void setRuleRatePre(Double ruleRatePre) {
        this.ruleRatePre = ruleRatePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_rate
     *
     * @return the value of game_rule.rule_rate
     *
     * @mbg.generated
     */
    public Double getRuleRate() {
        return ruleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_rate
     *
     * @param ruleRate the value for game_rule.rule_rate
     *
     * @mbg.generated
     */
    public void setRuleRate(Double ruleRate) {
        this.ruleRate = ruleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.rule_level
     *
     * @return the value of game_rule.rule_level
     *
     * @mbg.generated
     */
    public Integer getRuleLevel() {
        return ruleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.rule_level
     *
     * @param ruleLevel the value for game_rule.rule_level
     *
     * @mbg.generated
     */
    public void setRuleLevel(Integer ruleLevel) {
        this.ruleLevel = ruleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.create_time
     *
     * @return the value of game_rule.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.create_time
     *
     * @param createTime the value for game_rule.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rule.update_time
     *
     * @return the value of game_rule.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rule.update_time
     *
     * @param updateTime the value for game_rule.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ruleId=").append(ruleId);
        sb.append(", ruleFlag=").append(ruleFlag);
        sb.append(", ruleOptPre=").append(ruleOptPre);
        sb.append(", ruleOpt=").append(ruleOpt);
        sb.append(", ruleName=").append(ruleName);
        sb.append(", ruleDesc=").append(ruleDesc);
        sb.append(", ruleItem=").append(ruleItem);
        sb.append(", ruleRatePre=").append(ruleRatePre);
        sb.append(", ruleRate=").append(ruleRate);
        sb.append(", ruleLevel=").append(ruleLevel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GameRule other = (GameRule) that;
        return (this.getRuleId() == null ? other.getRuleId() == null : this.getRuleId().equals(other.getRuleId()))
            && (this.getRuleFlag() == null ? other.getRuleFlag() == null : this.getRuleFlag().equals(other.getRuleFlag()))
            && (this.getRuleOptPre() == null ? other.getRuleOptPre() == null : this.getRuleOptPre().equals(other.getRuleOptPre()))
            && (this.getRuleOpt() == null ? other.getRuleOpt() == null : this.getRuleOpt().equals(other.getRuleOpt()))
            && (this.getRuleName() == null ? other.getRuleName() == null : this.getRuleName().equals(other.getRuleName()))
            && (this.getRuleDesc() == null ? other.getRuleDesc() == null : this.getRuleDesc().equals(other.getRuleDesc()))
            && (this.getRuleItem() == null ? other.getRuleItem() == null : this.getRuleItem().equals(other.getRuleItem()))
            && (this.getRuleRatePre() == null ? other.getRuleRatePre() == null : this.getRuleRatePre().equals(other.getRuleRatePre()))
            && (this.getRuleRate() == null ? other.getRuleRate() == null : this.getRuleRate().equals(other.getRuleRate()))
            && (this.getRuleLevel() == null ? other.getRuleLevel() == null : this.getRuleLevel().equals(other.getRuleLevel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRuleId() == null) ? 0 : getRuleId().hashCode());
        result = prime * result + ((getRuleFlag() == null) ? 0 : getRuleFlag().hashCode());
        result = prime * result + ((getRuleOptPre() == null) ? 0 : getRuleOptPre().hashCode());
        result = prime * result + ((getRuleOpt() == null) ? 0 : getRuleOpt().hashCode());
        result = prime * result + ((getRuleName() == null) ? 0 : getRuleName().hashCode());
        result = prime * result + ((getRuleDesc() == null) ? 0 : getRuleDesc().hashCode());
        result = prime * result + ((getRuleItem() == null) ? 0 : getRuleItem().hashCode());
        result = prime * result + ((getRuleRatePre() == null) ? 0 : getRuleRatePre().hashCode());
        result = prime * result + ((getRuleRate() == null) ? 0 : getRuleRate().hashCode());
        result = prime * result + ((getRuleLevel() == null) ? 0 : getRuleLevel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public enum Column {
        ruleId("rule_id", "ruleId", "INTEGER", false),
        ruleFlag("rule_flag", "ruleFlag", "VARCHAR", false),
        ruleOptPre("rule_opt_pre", "ruleOptPre", "VARCHAR", false),
        ruleOpt("rule_opt", "ruleOpt", "VARCHAR", false),
        ruleName("rule_name", "ruleName", "VARCHAR", false),
        ruleDesc("rule_desc", "ruleDesc", "VARCHAR", false),
        ruleItem("rule_item", "ruleItem", "INTEGER", false),
        ruleRatePre("rule_rate_pre", "ruleRatePre", "DOUBLE", false),
        ruleRate("rule_rate", "ruleRate", "DOUBLE", false),
        ruleLevel("rule_level", "ruleLevel", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}