package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class GameTreeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public GameTreeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public GameTreeExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public GameTreeExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        GameTreeExample example = new GameTreeExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public GameTreeExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public GameTreeExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTreeIdIsNull() {
            addCriterion("tree_id is null");
            return (Criteria) this;
        }

        public Criteria andTreeIdIsNotNull() {
            addCriterion("tree_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreeIdEqualTo(Integer value) {
            addCriterion("tree_id =", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdNotEqualTo(Integer value) {
            addCriterion("tree_id <>", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdGreaterThan(Integer value) {
            addCriterion("tree_id >", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tree_id >=", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdLessThan(Integer value) {
            addCriterion("tree_id <", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdLessThanOrEqualTo(Integer value) {
            addCriterion("tree_id <=", value, "treeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeIdLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeIdIn(List<Integer> values) {
            addCriterion("tree_id in", values, "treeId");
            return (Criteria) this;
        }

        public Criteria andTreeIdNotIn(List<Integer> values) {
            addCriterion("tree_id not in", values, "treeId");
            return (Criteria) this;
        }

        public Criteria andTreeIdBetween(Integer value1, Integer value2) {
            addCriterion("tree_id between", value1, value2, "treeId");
            return (Criteria) this;
        }

        public Criteria andTreeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tree_id not between", value1, value2, "treeId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdIsNull() {
            addCriterion("tree_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdIsNotNull() {
            addCriterion("tree_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdEqualTo(String value) {
            addCriterion("tree_parent_id =", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdNotEqualTo(String value) {
            addCriterion("tree_parent_id <>", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdGreaterThan(String value) {
            addCriterion("tree_parent_id >", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("tree_parent_id >=", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdLessThan(String value) {
            addCriterion("tree_parent_id <", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdLessThanOrEqualTo(String value) {
            addCriterion("tree_parent_id <=", value, "treeParentId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeParentIdLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_parent_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeParentIdLike(String value) {
            addCriterion("tree_parent_id like", value, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdNotLike(String value) {
            addCriterion("tree_parent_id not like", value, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdIn(List<String> values) {
            addCriterion("tree_parent_id in", values, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdNotIn(List<String> values) {
            addCriterion("tree_parent_id not in", values, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdBetween(String value1, String value2) {
            addCriterion("tree_parent_id between", value1, value2, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreeParentIdNotBetween(String value1, String value2) {
            addCriterion("tree_parent_id not between", value1, value2, "treeParentId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdIsNull() {
            addCriterion("tree_player_id is null");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdIsNotNull() {
            addCriterion("tree_player_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdEqualTo(String value) {
            addCriterion("tree_player_id =", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdNotEqualTo(String value) {
            addCriterion("tree_player_id <>", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdGreaterThan(String value) {
            addCriterion("tree_player_id >", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("tree_player_id >=", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdLessThan(String value) {
            addCriterion("tree_player_id <", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdLessThanOrEqualTo(String value) {
            addCriterion("tree_player_id <=", value, "treePlayerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreePlayerIdLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_player_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdLike(String value) {
            addCriterion("tree_player_id like", value, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdNotLike(String value) {
            addCriterion("tree_player_id not like", value, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdIn(List<String> values) {
            addCriterion("tree_player_id in", values, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdNotIn(List<String> values) {
            addCriterion("tree_player_id not in", values, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdBetween(String value1, String value2) {
            addCriterion("tree_player_id between", value1, value2, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreePlayerIdNotBetween(String value1, String value2) {
            addCriterion("tree_player_id not between", value1, value2, "treePlayerId");
            return (Criteria) this;
        }

        public Criteria andTreeRelationIsNull() {
            addCriterion("tree_relation is null");
            return (Criteria) this;
        }

        public Criteria andTreeRelationIsNotNull() {
            addCriterion("tree_relation is not null");
            return (Criteria) this;
        }

        public Criteria andTreeRelationEqualTo(String value) {
            addCriterion("tree_relation =", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationNotEqualTo(String value) {
            addCriterion("tree_relation <>", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationGreaterThan(String value) {
            addCriterion("tree_relation >", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationGreaterThanOrEqualTo(String value) {
            addCriterion("tree_relation >=", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationLessThan(String value) {
            addCriterion("tree_relation <", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationLessThanOrEqualTo(String value) {
            addCriterion("tree_relation <=", value, "treeRelation");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeRelationLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_relation <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeRelationLike(String value) {
            addCriterion("tree_relation like", value, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andTreeRelationNotLike(String value) {
            addCriterion("tree_relation not like", value, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andTreeRelationIn(List<String> values) {
            addCriterion("tree_relation in", values, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andTreeRelationNotIn(List<String> values) {
            addCriterion("tree_relation not in", values, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andTreeRelationBetween(String value1, String value2) {
            addCriterion("tree_relation between", value1, value2, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andTreeRelationNotBetween(String value1, String value2) {
            addCriterion("tree_relation not between", value1, value2, "treeRelation");
            return (Criteria) this;
        }

        public Criteria andSendAutoIsNull() {
            addCriterion("send_auto is null");
            return (Criteria) this;
        }

        public Criteria andSendAutoIsNotNull() {
            addCriterion("send_auto is not null");
            return (Criteria) this;
        }

        public Criteria andSendAutoEqualTo(String value) {
            addCriterion("send_auto =", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoNotEqualTo(String value) {
            addCriterion("send_auto <>", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoGreaterThan(String value) {
            addCriterion("send_auto >", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoGreaterThanOrEqualTo(String value) {
            addCriterion("send_auto >=", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoLessThan(String value) {
            addCriterion("send_auto <", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoLessThanOrEqualTo(String value) {
            addCriterion("send_auto <=", value, "sendAuto");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andSendAutoLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("send_auto <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendAutoLike(String value) {
            addCriterion("send_auto like", value, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andSendAutoNotLike(String value) {
            addCriterion("send_auto not like", value, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andSendAutoIn(List<String> values) {
            addCriterion("send_auto in", values, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andSendAutoNotIn(List<String> values) {
            addCriterion("send_auto not in", values, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andSendAutoBetween(String value1, String value2) {
            addCriterion("send_auto between", value1, value2, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andSendAutoNotBetween(String value1, String value2) {
            addCriterion("send_auto not between", value1, value2, "sendAuto");
            return (Criteria) this;
        }

        public Criteria andTreeLevelIsNull() {
            addCriterion("tree_level is null");
            return (Criteria) this;
        }

        public Criteria andTreeLevelIsNotNull() {
            addCriterion("tree_level is not null");
            return (Criteria) this;
        }

        public Criteria andTreeLevelEqualTo(Integer value) {
            addCriterion("tree_level =", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelNotEqualTo(Integer value) {
            addCriterion("tree_level <>", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelGreaterThan(Integer value) {
            addCriterion("tree_level >", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("tree_level >=", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelLessThan(Integer value) {
            addCriterion("tree_level <", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelLessThanOrEqualTo(Integer value) {
            addCriterion("tree_level <=", value, "treeLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeLevelLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_level <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeLevelIn(List<Integer> values) {
            addCriterion("tree_level in", values, "treeLevel");
            return (Criteria) this;
        }

        public Criteria andTreeLevelNotIn(List<Integer> values) {
            addCriterion("tree_level not in", values, "treeLevel");
            return (Criteria) this;
        }

        public Criteria andTreeLevelBetween(Integer value1, Integer value2) {
            addCriterion("tree_level between", value1, value2, "treeLevel");
            return (Criteria) this;
        }

        public Criteria andTreeLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("tree_level not between", value1, value2, "treeLevel");
            return (Criteria) this;
        }

        public Criteria andTreeChildsIsNull() {
            addCriterion("tree_childs is null");
            return (Criteria) this;
        }

        public Criteria andTreeChildsIsNotNull() {
            addCriterion("tree_childs is not null");
            return (Criteria) this;
        }

        public Criteria andTreeChildsEqualTo(Integer value) {
            addCriterion("tree_childs =", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsNotEqualTo(Integer value) {
            addCriterion("tree_childs <>", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsGreaterThan(Integer value) {
            addCriterion("tree_childs >", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsGreaterThanOrEqualTo(Integer value) {
            addCriterion("tree_childs >=", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsLessThan(Integer value) {
            addCriterion("tree_childs <", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsLessThanOrEqualTo(Integer value) {
            addCriterion("tree_childs <=", value, "treeChilds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeChildsLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_childs <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeChildsIn(List<Integer> values) {
            addCriterion("tree_childs in", values, "treeChilds");
            return (Criteria) this;
        }

        public Criteria andTreeChildsNotIn(List<Integer> values) {
            addCriterion("tree_childs not in", values, "treeChilds");
            return (Criteria) this;
        }

        public Criteria andTreeChildsBetween(Integer value1, Integer value2) {
            addCriterion("tree_childs between", value1, value2, "treeChilds");
            return (Criteria) this;
        }

        public Criteria andTreeChildsNotBetween(Integer value1, Integer value2) {
            addCriterion("tree_childs not between", value1, value2, "treeChilds");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonIsNull() {
            addCriterion("tree_grandson is null");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonIsNotNull() {
            addCriterion("tree_grandson is not null");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonEqualTo(Integer value) {
            addCriterion("tree_grandson =", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonNotEqualTo(Integer value) {
            addCriterion("tree_grandson <>", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonGreaterThan(Integer value) {
            addCriterion("tree_grandson >", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonGreaterThanOrEqualTo(Integer value) {
            addCriterion("tree_grandson >=", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonLessThan(Integer value) {
            addCriterion("tree_grandson <", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonLessThanOrEqualTo(Integer value) {
            addCriterion("tree_grandson <=", value, "treeGrandson");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andTreeGrandsonLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("tree_grandson <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonIn(List<Integer> values) {
            addCriterion("tree_grandson in", values, "treeGrandson");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonNotIn(List<Integer> values) {
            addCriterion("tree_grandson not in", values, "treeGrandson");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonBetween(Integer value1, Integer value2) {
            addCriterion("tree_grandson between", value1, value2, "treeGrandson");
            return (Criteria) this;
        }

        public Criteria andTreeGrandsonNotBetween(Integer value1, Integer value2) {
            addCriterion("tree_grandson not between", value1, value2, "treeGrandson");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(GameTree.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_tree
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private GameTreeExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        protected Criteria(GameTreeExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public GameTreeExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table game_tree
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.GameTreeExample example);
    }
}