package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class GameRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public GameRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public GameRuleExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public GameRuleExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        GameRuleExample example = new GameRuleExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public GameRuleExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public GameRuleExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("rule_id is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("rule_id is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(Integer value) {
            addCriterion("rule_id =", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(Integer value) {
            addCriterion("rule_id <>", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(Integer value) {
            addCriterion("rule_id >", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_id >=", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(Integer value) {
            addCriterion("rule_id <", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("rule_id <=", value, "ruleId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleIdLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<Integer> values) {
            addCriterion("rule_id in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<Integer> values) {
            addCriterion("rule_id not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(Integer value1, Integer value2) {
            addCriterion("rule_id between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_id not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleFlagIsNull() {
            addCriterion("rule_flag is null");
            return (Criteria) this;
        }

        public Criteria andRuleFlagIsNotNull() {
            addCriterion("rule_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRuleFlagEqualTo(String value) {
            addCriterion("rule_flag =", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagNotEqualTo(String value) {
            addCriterion("rule_flag <>", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagGreaterThan(String value) {
            addCriterion("rule_flag >", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagGreaterThanOrEqualTo(String value) {
            addCriterion("rule_flag >=", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagLessThan(String value) {
            addCriterion("rule_flag <", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagLessThanOrEqualTo(String value) {
            addCriterion("rule_flag <=", value, "ruleFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleFlagLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_flag <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleFlagLike(String value) {
            addCriterion("rule_flag like", value, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleFlagNotLike(String value) {
            addCriterion("rule_flag not like", value, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleFlagIn(List<String> values) {
            addCriterion("rule_flag in", values, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleFlagNotIn(List<String> values) {
            addCriterion("rule_flag not in", values, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleFlagBetween(String value1, String value2) {
            addCriterion("rule_flag between", value1, value2, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleFlagNotBetween(String value1, String value2) {
            addCriterion("rule_flag not between", value1, value2, "ruleFlag");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreIsNull() {
            addCriterion("rule_opt_pre is null");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreIsNotNull() {
            addCriterion("rule_opt_pre is not null");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreEqualTo(String value) {
            addCriterion("rule_opt_pre =", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreNotEqualTo(String value) {
            addCriterion("rule_opt_pre <>", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreGreaterThan(String value) {
            addCriterion("rule_opt_pre >", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreGreaterThanOrEqualTo(String value) {
            addCriterion("rule_opt_pre >=", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreLessThan(String value) {
            addCriterion("rule_opt_pre <", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreLessThanOrEqualTo(String value) {
            addCriterion("rule_opt_pre <=", value, "ruleOptPre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptPreLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt_pre <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptPreLike(String value) {
            addCriterion("rule_opt_pre like", value, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreNotLike(String value) {
            addCriterion("rule_opt_pre not like", value, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreIn(List<String> values) {
            addCriterion("rule_opt_pre in", values, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreNotIn(List<String> values) {
            addCriterion("rule_opt_pre not in", values, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreBetween(String value1, String value2) {
            addCriterion("rule_opt_pre between", value1, value2, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptPreNotBetween(String value1, String value2) {
            addCriterion("rule_opt_pre not between", value1, value2, "ruleOptPre");
            return (Criteria) this;
        }

        public Criteria andRuleOptIsNull() {
            addCriterion("rule_opt is null");
            return (Criteria) this;
        }

        public Criteria andRuleOptIsNotNull() {
            addCriterion("rule_opt is not null");
            return (Criteria) this;
        }

        public Criteria andRuleOptEqualTo(String value) {
            addCriterion("rule_opt =", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptNotEqualTo(String value) {
            addCriterion("rule_opt <>", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptGreaterThan(String value) {
            addCriterion("rule_opt >", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptGreaterThanOrEqualTo(String value) {
            addCriterion("rule_opt >=", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptLessThan(String value) {
            addCriterion("rule_opt <", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptLessThanOrEqualTo(String value) {
            addCriterion("rule_opt <=", value, "ruleOpt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleOptLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_opt <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleOptLike(String value) {
            addCriterion("rule_opt like", value, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleOptNotLike(String value) {
            addCriterion("rule_opt not like", value, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleOptIn(List<String> values) {
            addCriterion("rule_opt in", values, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleOptNotIn(List<String> values) {
            addCriterion("rule_opt not in", values, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleOptBetween(String value1, String value2) {
            addCriterion("rule_opt between", value1, value2, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleOptNotBetween(String value1, String value2) {
            addCriterion("rule_opt not between", value1, value2, "ruleOpt");
            return (Criteria) this;
        }

        public Criteria andRuleNameIsNull() {
            addCriterion("rule_name is null");
            return (Criteria) this;
        }

        public Criteria andRuleNameIsNotNull() {
            addCriterion("rule_name is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNameEqualTo(String value) {
            addCriterion("rule_name =", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameNotEqualTo(String value) {
            addCriterion("rule_name <>", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameGreaterThan(String value) {
            addCriterion("rule_name >", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("rule_name >=", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameLessThan(String value) {
            addCriterion("rule_name <", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameLessThanOrEqualTo(String value) {
            addCriterion("rule_name <=", value, "ruleName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleNameLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleNameLike(String value) {
            addCriterion("rule_name like", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotLike(String value) {
            addCriterion("rule_name not like", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameIn(List<String> values) {
            addCriterion("rule_name in", values, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotIn(List<String> values) {
            addCriterion("rule_name not in", values, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameBetween(String value1, String value2) {
            addCriterion("rule_name between", value1, value2, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotBetween(String value1, String value2) {
            addCriterion("rule_name not between", value1, value2, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleDescIsNull() {
            addCriterion("rule_desc is null");
            return (Criteria) this;
        }

        public Criteria andRuleDescIsNotNull() {
            addCriterion("rule_desc is not null");
            return (Criteria) this;
        }

        public Criteria andRuleDescEqualTo(String value) {
            addCriterion("rule_desc =", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescNotEqualTo(String value) {
            addCriterion("rule_desc <>", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescGreaterThan(String value) {
            addCriterion("rule_desc >", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescGreaterThanOrEqualTo(String value) {
            addCriterion("rule_desc >=", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescLessThan(String value) {
            addCriterion("rule_desc <", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescLessThanOrEqualTo(String value) {
            addCriterion("rule_desc <=", value, "ruleDesc");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleDescLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_desc <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleDescLike(String value) {
            addCriterion("rule_desc like", value, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleDescNotLike(String value) {
            addCriterion("rule_desc not like", value, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleDescIn(List<String> values) {
            addCriterion("rule_desc in", values, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleDescNotIn(List<String> values) {
            addCriterion("rule_desc not in", values, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleDescBetween(String value1, String value2) {
            addCriterion("rule_desc between", value1, value2, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleDescNotBetween(String value1, String value2) {
            addCriterion("rule_desc not between", value1, value2, "ruleDesc");
            return (Criteria) this;
        }

        public Criteria andRuleItemIsNull() {
            addCriterion("rule_item is null");
            return (Criteria) this;
        }

        public Criteria andRuleItemIsNotNull() {
            addCriterion("rule_item is not null");
            return (Criteria) this;
        }

        public Criteria andRuleItemEqualTo(Integer value) {
            addCriterion("rule_item =", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemNotEqualTo(Integer value) {
            addCriterion("rule_item <>", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemGreaterThan(Integer value) {
            addCriterion("rule_item >", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_item >=", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemLessThan(Integer value) {
            addCriterion("rule_item <", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemLessThanOrEqualTo(Integer value) {
            addCriterion("rule_item <=", value, "ruleItem");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleItemLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_item <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleItemIn(List<Integer> values) {
            addCriterion("rule_item in", values, "ruleItem");
            return (Criteria) this;
        }

        public Criteria andRuleItemNotIn(List<Integer> values) {
            addCriterion("rule_item not in", values, "ruleItem");
            return (Criteria) this;
        }

        public Criteria andRuleItemBetween(Integer value1, Integer value2) {
            addCriterion("rule_item between", value1, value2, "ruleItem");
            return (Criteria) this;
        }

        public Criteria andRuleItemNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_item not between", value1, value2, "ruleItem");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreIsNull() {
            addCriterion("rule_rate_pre is null");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreIsNotNull() {
            addCriterion("rule_rate_pre is not null");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreEqualTo(Double value) {
            addCriterion("rule_rate_pre =", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreNotEqualTo(Double value) {
            addCriterion("rule_rate_pre <>", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreGreaterThan(Double value) {
            addCriterion("rule_rate_pre >", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreGreaterThanOrEqualTo(Double value) {
            addCriterion("rule_rate_pre >=", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreLessThan(Double value) {
            addCriterion("rule_rate_pre <", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreLessThanOrEqualTo(Double value) {
            addCriterion("rule_rate_pre <=", value, "ruleRatePre");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRatePreLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate_pre <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRatePreIn(List<Double> values) {
            addCriterion("rule_rate_pre in", values, "ruleRatePre");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreNotIn(List<Double> values) {
            addCriterion("rule_rate_pre not in", values, "ruleRatePre");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreBetween(Double value1, Double value2) {
            addCriterion("rule_rate_pre between", value1, value2, "ruleRatePre");
            return (Criteria) this;
        }

        public Criteria andRuleRatePreNotBetween(Double value1, Double value2) {
            addCriterion("rule_rate_pre not between", value1, value2, "ruleRatePre");
            return (Criteria) this;
        }

        public Criteria andRuleRateIsNull() {
            addCriterion("rule_rate is null");
            return (Criteria) this;
        }

        public Criteria andRuleRateIsNotNull() {
            addCriterion("rule_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRuleRateEqualTo(Double value) {
            addCriterion("rule_rate =", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateNotEqualTo(Double value) {
            addCriterion("rule_rate <>", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateGreaterThan(Double value) {
            addCriterion("rule_rate >", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateGreaterThanOrEqualTo(Double value) {
            addCriterion("rule_rate >=", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateLessThan(Double value) {
            addCriterion("rule_rate <", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateLessThanOrEqualTo(Double value) {
            addCriterion("rule_rate <=", value, "ruleRate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleRateLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_rate <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleRateIn(List<Double> values) {
            addCriterion("rule_rate in", values, "ruleRate");
            return (Criteria) this;
        }

        public Criteria andRuleRateNotIn(List<Double> values) {
            addCriterion("rule_rate not in", values, "ruleRate");
            return (Criteria) this;
        }

        public Criteria andRuleRateBetween(Double value1, Double value2) {
            addCriterion("rule_rate between", value1, value2, "ruleRate");
            return (Criteria) this;
        }

        public Criteria andRuleRateNotBetween(Double value1, Double value2) {
            addCriterion("rule_rate not between", value1, value2, "ruleRate");
            return (Criteria) this;
        }

        public Criteria andRuleLevelIsNull() {
            addCriterion("rule_level is null");
            return (Criteria) this;
        }

        public Criteria andRuleLevelIsNotNull() {
            addCriterion("rule_level is not null");
            return (Criteria) this;
        }

        public Criteria andRuleLevelEqualTo(Integer value) {
            addCriterion("rule_level =", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelNotEqualTo(Integer value) {
            addCriterion("rule_level <>", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelGreaterThan(Integer value) {
            addCriterion("rule_level >", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_level >=", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelLessThan(Integer value) {
            addCriterion("rule_level <", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelLessThanOrEqualTo(Integer value) {
            addCriterion("rule_level <=", value, "ruleLevel");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andRuleLevelLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("rule_level <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andRuleLevelIn(List<Integer> values) {
            addCriterion("rule_level in", values, "ruleLevel");
            return (Criteria) this;
        }

        public Criteria andRuleLevelNotIn(List<Integer> values) {
            addCriterion("rule_level not in", values, "ruleLevel");
            return (Criteria) this;
        }

        public Criteria andRuleLevelBetween(Integer value1, Integer value2) {
            addCriterion("rule_level between", value1, value2, "ruleLevel");
            return (Criteria) this;
        }

        public Criteria andRuleLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_level not between", value1, value2, "ruleLevel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(GameRule.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_rule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        private GameRuleExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        protected Criteria(GameRuleExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public GameRuleExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table game_rule
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_rule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_rule
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.GameRuleExample example);
    }
}