package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class GameTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_id
     *
     * @mbg.generated
     */
    private Integer treeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_parent_id
     *
     * @mbg.generated
     */
    private String treeParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_player_id
     *
     * @mbg.generated
     */
    private String treePlayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_relation
     *
     * @mbg.generated
     */
    private String treeRelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.send_auto
     *
     * @mbg.generated
     */
    private String sendAuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_level
     *
     * @mbg.generated
     */
    private Integer treeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_childs
     *
     * @mbg.generated
     */
    private Integer treeChilds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.tree_grandson
     *
     * @mbg.generated
     */
    private Integer treeGrandson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tree.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_id
     *
     * @return the value of game_tree.tree_id
     *
     * @mbg.generated
     */
    public Integer getTreeId() {
        return treeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_id
     *
     * @param treeId the value for game_tree.tree_id
     *
     * @mbg.generated
     */
    public void setTreeId(Integer treeId) {
        this.treeId = treeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_parent_id
     *
     * @return the value of game_tree.tree_parent_id
     *
     * @mbg.generated
     */
    public String getTreeParentId() {
        return treeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_parent_id
     *
     * @param treeParentId the value for game_tree.tree_parent_id
     *
     * @mbg.generated
     */
    public void setTreeParentId(String treeParentId) {
        this.treeParentId = treeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_player_id
     *
     * @return the value of game_tree.tree_player_id
     *
     * @mbg.generated
     */
    public String getTreePlayerId() {
        return treePlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_player_id
     *
     * @param treePlayerId the value for game_tree.tree_player_id
     *
     * @mbg.generated
     */
    public void setTreePlayerId(String treePlayerId) {
        this.treePlayerId = treePlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_relation
     *
     * @return the value of game_tree.tree_relation
     *
     * @mbg.generated
     */
    public String getTreeRelation() {
        return treeRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_relation
     *
     * @param treeRelation the value for game_tree.tree_relation
     *
     * @mbg.generated
     */
    public void setTreeRelation(String treeRelation) {
        this.treeRelation = treeRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.send_auto
     *
     * @return the value of game_tree.send_auto
     *
     * @mbg.generated
     */
    public String getSendAuto() {
        return sendAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.send_auto
     *
     * @param sendAuto the value for game_tree.send_auto
     *
     * @mbg.generated
     */
    public void setSendAuto(String sendAuto) {
        this.sendAuto = sendAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_level
     *
     * @return the value of game_tree.tree_level
     *
     * @mbg.generated
     */
    public Integer getTreeLevel() {
        return treeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_level
     *
     * @param treeLevel the value for game_tree.tree_level
     *
     * @mbg.generated
     */
    public void setTreeLevel(Integer treeLevel) {
        this.treeLevel = treeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_childs
     *
     * @return the value of game_tree.tree_childs
     *
     * @mbg.generated
     */
    public Integer getTreeChilds() {
        return treeChilds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_childs
     *
     * @param treeChilds the value for game_tree.tree_childs
     *
     * @mbg.generated
     */
    public void setTreeChilds(Integer treeChilds) {
        this.treeChilds = treeChilds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.tree_grandson
     *
     * @return the value of game_tree.tree_grandson
     *
     * @mbg.generated
     */
    public Integer getTreeGrandson() {
        return treeGrandson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.tree_grandson
     *
     * @param treeGrandson the value for game_tree.tree_grandson
     *
     * @mbg.generated
     */
    public void setTreeGrandson(Integer treeGrandson) {
        this.treeGrandson = treeGrandson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tree.create_time
     *
     * @return the value of game_tree.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tree.create_time
     *
     * @param createTime the value for game_tree.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", treeId=").append(treeId);
        sb.append(", treeParentId=").append(treeParentId);
        sb.append(", treePlayerId=").append(treePlayerId);
        sb.append(", treeRelation=").append(treeRelation);
        sb.append(", sendAuto=").append(sendAuto);
        sb.append(", treeLevel=").append(treeLevel);
        sb.append(", treeChilds=").append(treeChilds);
        sb.append(", treeGrandson=").append(treeGrandson);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GameTree other = (GameTree) that;
        return (this.getTreeId() == null ? other.getTreeId() == null : this.getTreeId().equals(other.getTreeId()))
            && (this.getTreeParentId() == null ? other.getTreeParentId() == null : this.getTreeParentId().equals(other.getTreeParentId()))
            && (this.getTreePlayerId() == null ? other.getTreePlayerId() == null : this.getTreePlayerId().equals(other.getTreePlayerId()))
            && (this.getTreeRelation() == null ? other.getTreeRelation() == null : this.getTreeRelation().equals(other.getTreeRelation()))
            && (this.getSendAuto() == null ? other.getSendAuto() == null : this.getSendAuto().equals(other.getSendAuto()))
            && (this.getTreeLevel() == null ? other.getTreeLevel() == null : this.getTreeLevel().equals(other.getTreeLevel()))
            && (this.getTreeChilds() == null ? other.getTreeChilds() == null : this.getTreeChilds().equals(other.getTreeChilds()))
            && (this.getTreeGrandson() == null ? other.getTreeGrandson() == null : this.getTreeGrandson().equals(other.getTreeGrandson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTreeId() == null) ? 0 : getTreeId().hashCode());
        result = prime * result + ((getTreeParentId() == null) ? 0 : getTreeParentId().hashCode());
        result = prime * result + ((getTreePlayerId() == null) ? 0 : getTreePlayerId().hashCode());
        result = prime * result + ((getTreeRelation() == null) ? 0 : getTreeRelation().hashCode());
        result = prime * result + ((getSendAuto() == null) ? 0 : getSendAuto().hashCode());
        result = prime * result + ((getTreeLevel() == null) ? 0 : getTreeLevel().hashCode());
        result = prime * result + ((getTreeChilds() == null) ? 0 : getTreeChilds().hashCode());
        result = prime * result + ((getTreeGrandson() == null) ? 0 : getTreeGrandson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table game_tree
     *
     * @mbg.generated
     */
    public enum Column {
        treeId("tree_id", "treeId", "INTEGER", false),
        treeParentId("tree_parent_id", "treeParentId", "VARCHAR", false),
        treePlayerId("tree_player_id", "treePlayerId", "VARCHAR", false),
        treeRelation("tree_relation", "treeRelation", "VARCHAR", false),
        sendAuto("send_auto", "sendAuto", "VARCHAR", false),
        treeLevel("tree_level", "treeLevel", "INTEGER", false),
        treeChilds("tree_childs", "treeChilds", "INTEGER", false),
        treeGrandson("tree_grandson", "treeGrandson", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table game_tree
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}